[versions]
kotlin-version = "1.9.22"
agp-version = "7.3.0"
compose-version = "1.6.1"
precompose = "1.6.0-rc04"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp.version" }
android-library = { id = "com.android.library", version.ref = "agp.version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin.version" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.10.1" }
androidx-activity-compose = "androidx.activity:activity-compose:1.8.0"
precompose = { module = "moe.tlaster:precompose", version.ref = "precompose" }
precompose-viewmodel = { module = "moe.tlaster:precompose-viewmodel", version.ref = "precompose" }
